version: "3.8"

services:
  zitadel:
    restart: "always"
    networks:
      - "zitadel"
    image: "ghcr.io/zitadel/zitadel:latest"
    command: 'start-from-init --masterkey "MasterkeyNeedsToHave32Characters" --tlsMode disabled'
    environment:
      - "ZITADEL_DATABASE_POSTGRES_HOST=db"
      - "ZITADEL_DATABASE_POSTGRES_PORT=5432"
      - "ZITADEL_DATABASE_POSTGRES_DATABASE=zitadel"
      - "ZITADEL_DATABASE_POSTGRES_USER_USERNAME=zitadel"
      - "ZITADEL_DATABASE_POSTGRES_USER_PASSWORD=zitadel"
      - "ZITADEL_DATABASE_POSTGRES_USER_SSL_MODE=disable"
      - "ZITADEL_DATABASE_POSTGRES_ADMIN_USERNAME=kati"
      - "ZITADEL_DATABASE_POSTGRES_ADMIN_PASSWORD=kati"
      - "ZITADEL_DATABASE_POSTGRES_ADMIN_SSL_MODE=disable"
      - "ZITADEL_EXTERNALSECURE=false"
      - "ZITADEL_EXTERNALDOMAIN=zitadel.kindergarten.test"
      - "ZITADEL_FIRSTINSTANCE_MACHINEKEYPATH=/machinekey/zitadel-admin-sa.json"
      - "ZITADEL_FIRSTINSTANCE_ORG_MACHINE_MACHINE_USERNAME=zitadel-admin-sa"
      - "ZITADEL_FIRSTINSTANCE_ORG_MACHINE_MACHINE_NAME=Admin"
      - "ZITADEL_FIRSTINSTANCE_ORG_MACHINE_MACHINEKEY_TYPE=1"
    depends_on:
      db:
        condition: "service_healthy"
    ports:
      - "9412:8080"
    volumes:
      - ./zitadel-machinekey:/machinekey

  db:
    restart: "always"
    image: postgres:16-alpine
    environment:
      - POSTGRES_USER=kati
      - POSTGRES_PASSWORD=kati
    networks:
      - "zitadel"
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U zitadel -d zitadel"]
      interval: "10s"
      timeout: "30s"
      retries: 5
      start_period: "20s"
    volumes:
      - ./Kindergarten_db:/var/lib/postgresql
      - ./src/db_init/:/docker-entrypoint-initdb.d

  adminer:
    image: adminer
    restart: always
    networks:
      - "zitadel"
    ports:
      - "9090:8080"

  mailhog:
    image: mailhog/mailhog
    environment:
      - "MH_HOSTNAME=mail.kindergarten.test"
    networks:
      - "zitadel"
    ports:
      - "8025:8025"

networks:
  zitadel:
